### ISSUE TITLE
The macro "BOARD_FLASH_SIZE" is not defined in sdk/devices/MIMXRT1064/project_template/board.h

### ISSUE THREAD

**Issue by Albort12138** [hathach/nxp_driver#1]
The repo is used by micropython project. When I enable MIMXRT1064, I found that there is a build error. It says that the macro "BOARD_FLASH_SIZE" is not defined. So I think the board.h in sdk/devices/MIMXRT1064/project_template/ should be updated.

**Comment by hathach** [comment]
where did mircopython defined this for other board, you can follow that to add a new board ? this repo files is imported as it is from NXP package. I think they expect each board to define its own flash size.

**Comment by Albort12138** [comment]
> where did mircopython defined this for other board, you can follow that to add a new board ? this repo files is imported as it is from NXP package. I think they expect each board to define its own flash size.

That macro is used in *fsl_flexspi_nor_boot.h* file and this file includes *board.h*, so the *BOARD_FLASH_SIZE* which is defined in the *board.h* is useful. And I think currently in micropython the *BAORD_FLASH_SIZE* defined in *ports/mimxrt/boards/{BOARD_NAME}/mpconfigboard.h*  is useless, because that header file is not included in *fsl_flexspi_nor_boot.h*.

The file in the template folder is used for NXP mcuxpresso IDE NPW(New project wizard), and it contains the default setting of the board.

**Comment by hathach** [comment]
If you think the way micropython is defined the macro is not right, you should open an issue/pr there for discussion. The template shouldn't be used as it is, you should modify it to fit your project, adding your own bsp or something. That file got imported as it is from NXP sdk, therefore I don't see any reason to modify it.
